import json
from pathlib import Path

result = {
  "nodes": [
    {"id": "proto_ref", "label": "FUTU_API_PROTO_REFERENCE", "file_type": "document", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": None},
    {"id": "python_ref", "label": "FUTU_API_PYTHON_REFERENCE", "file_type": "document", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": None},
    {"id": "1001", "label": "InitConnect", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "16-36"},
    {"id": "1002", "label": "GetGlobalState", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "11"},
    {"id": "1003", "label": "Notify", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "11"},
    {"id": "1004", "label": "KeepAlive", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "43-80"},
    {"id": "3001", "label": "QOT_SUB", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "335"},
    {"id": "3002", "label": "QOT_REG_QOT_PUSH", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "336"},
    {"id": "3006", "label": "QOT_GET_KL", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "340"},
    {"id": "3008", "label": "QOT_GET_RT", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "342"},
    {"id": "3010", "label": "QOT_GET_TICKER", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "344"},
    {"id": "3012", "label": "QOT_GET_ORDER_BOOK", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "346"},
    {"id": "3014", "label": "QOT_GET_BROKER", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "348"},
    {"id": "3100", "label": "QOT_GET_HISTORY_KL", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "350"},
    {"id": "3200", "label": "QOT_GET_TRADE_DATE", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "352"},
    {"id": "3203", "label": "QOT_GET_SECURITY_SNAPSHOT", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "353"},
    {"id": "3204", "label": "QOT_GET_PLATE_SET", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "354"},
    {"id": "3205", "label": "QOT_GET_PLATE_SECURITY", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "355"},
    {"id": "3209", "label": "QOT_GET_OPTION_CHAIN", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "356"},
    {"id": "2001", "label": "TRD_GET_ACC_LIST", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "362"},
    {"id": "2005", "label": "TRD_UNLOCK_TRADE", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "363"},
    {"id": "2101", "label": "TRD_GET_FUNDS", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "364"},
    {"id": "2102", "label": "TRD_GET_POSITION_LIST", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "365"},
    {"id": "2201", "label": "TRD_GET_ORDER_LIST", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "366"},
    {"id": "2202", "label": "TRD_PLACE_ORDER", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "367"},
    {"id": "2205", "label": "TRD_MODIFY_ORDER", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "368"},
    {"id": "2211", "label": "TRD_GET_ORDER_FILL_LIST", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "369"},
    {"id": "2221", "label": "TRD_GET_HISTORY_ORDER_LIST", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "370"},
    {"id": "2222", "label": "TRD_GET_HISTORY_ORDER_FILL_LIST", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "371"},
    {"id": "protobuf", "label": "Protobuf", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "104"},
    {"id": "json_fmt", "label": "Json", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "105"},
    {"id": "rsa_enc", "label": "RSA Encryption", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "32-36"},
    {"id": "aes_enc", "label": "AES Encryption", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "312-317"},
    {"id": "ret_type", "label": "RetType", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "86-96"},
    {"id": "proto_fmt", "label": "ProtoFmt", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "100-107"},
    {"id": "packet_enc_algo", "label": "PacketEncAlgo", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "109-120"},
    {"id": "program_status_type", "label": "ProgramStatusType", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "122-142"},
    {"id": "gtw_event_type", "label": "GtwEventType", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "144-167"},
    {"id": "notify_type", "label": "NotifyType", "file_type": "concept", "source_file": "docs/FUTU_API_PROTO_REFERENCE.md", "source_location": "169-183"},
    {"id": "opend", "label": "OpenD", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "11"},
    {"id": "openquotecontext", "label": "OpenQuoteContext", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "102"},
    {"id": "opensectradecontext", "label": "OpenSecTradeContext", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "105"},
    {"id": "trdenv", "label": "TrdEnv", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "84-85"},
    {"id": "get_market_snapshot", "label": "get_market_snapshot", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "35"},
    {"id": "get_stock_quote", "label": "get_stock_quote", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "36"},
    {"id": "get_cur_kline", "label": "get_cur_kline", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "39"},
    {"id": "get_history_kline", "label": "get_history_kline", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "40"},
    {"id": "get_order_book", "label": "get_order_book", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "44"},
    {"id": "get_ticker", "label": "get_ticker", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "47"},
    {"id": "get_stock_time_sharing", "label": "get_stock_time_sharing", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "50"},
    {"id": "get_capital_flow", "label": "get_capital_flow", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "56"},
    {"id": "get_plate_set", "label": "get_plate_set", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "60"},
    {"id": "get_plate_stock", "label": "get_plate_stock", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "61"},
    {"id": "place_order", "label": "place_order", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "73"},
    {"id": "cancel_order", "label": "cancel_order", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "74"},
    {"id": "modify_order", "label": "modify_order", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "75"},
    {"id": "subscribe", "label": "subscribe", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "67"},
    {"id": "unsubscribe", "label": "unsubscribe", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "68"},
    {"id": "futu_id", "label": "Futu ID", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "15"},
    {"id": "universal_account", "label": "Universal Account", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "16"},
    {"id": "quotation", "label": "Quotation", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "19"},
    {"id": "trading", "label": "Trading", "file_type": "concept", "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md", "source_location": "20"}
  ],
  "edges": [
    {"source": "1001", "target": "rsa_enc", "relation": "uses_encryption", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "1004", "target": "1001", "relation": "depends_on", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "proto_fmt", "target": "protobuf", "relation": "includes", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "proto_fmt", "target": "json_fmt", "relation": "includes", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "packet_enc_algo", "target": "aes_enc", "relation": "includes", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "rsa_enc", "target": "aes_enc", "relation": "combined_with", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "opend", "target": "openquotecontext", "relation": "provides", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "opend", "target": "opensectradecontext", "relation": "provides", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "trdenv", "target": "trading", "relation": "enables", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "subscribe", "target": "3001", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_stock_quote", "target": "3001", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.7, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_cur_kline", "target": "3006", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_history_kline", "target": "3100", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_ticker", "target": "3010", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_order_book", "target": "3012", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_stock_time_sharing", "target": "3008", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.7, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_plate_set", "target": "3204", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "get_plate_stock", "target": "3205", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "place_order", "target": "2202", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "cancel_order", "target": "2201", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.7, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "modify_order", "target": "2205", "relation": "maps_to", "confidence": "INFERRED", "confidence_score": 0.8, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "3001", "target": "protobuf", "relation": "uses_format", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "3001", "target": "json_fmt", "relation": "uses_format", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "python_ref", "target": "opend", "relation": "documents", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "python_ref", "target": "trdenv", "relation": "documents", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "proto_ref", "target": "1001", "relation": "documents", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "proto_ref", "target": "1004", "relation": "documents", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PROTO_REFERENCE.md"},
    {"source": "quotation", "target": "get_market_snapshot", "relation": "provides", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"},
    {"source": "trading", "target": "place_order", "relation": "includes", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "docs/FUTU_API_PYTHON_REFERENCE.md"}
  ],
  "hyperedges": [],
  "input_tokens": 5000,
  "output_tokens": 2000
}

Path('graphify-out/.graphify_api_docs.json').write_text(json.dumps(result, indent=2))
print('Saved API docs: ' + str(len(result['nodes'])) + ' nodes, ' + str(len(result['edges'])) + ' edges')